apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: target
      value: DevOps-Engineer
    - name: duration
      value: 2-months
    