kind: Service
apiVersion: v1 
metadata:
  name: nginx
spec:
  selector:
    project: expense
    component: fronted
    environment: dev
    version: "1.0.0"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx
  labels:
    project: expense
    component: fronted
    environment: dev
    version: "1.0.0"
spec:
  containers:
  - name: nginx
    image: nginx
